version: "3.9"
services:
  django:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_NAME=app_db
      - DB_USER=root
      - DB_PASSWORD=1234
    networks:
      - backend
  mysql:
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=app_db
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend
networks:
  backend:
volumes:
  mysql-data: